Remove netcdf4 from conda environments
This reverts the changes in 53cfc87 and c005859.

Eventually I think we'll want netcdf4 in these conda environments. But
it was causing problems on my Mac:

FAILED src/esmpy/test/test_api/test_mesh.py::TestMesh::test_mesh_create_from_file_scrip - ValueError: ESMC_MeshCreateFromFile() failed with rc = 67.    Please check ...
FAILED src/esmpy/test/test_api/test_mesh.py::TestMesh::test_slice_mesh_created_from_file_scrip - ValueError: ESMC_MeshCreateFromFile() failed with rc = 67.    Please check ...
FAILED src/esmpy/test/regrid_from_file/test_regrid_from_file.py::test_run_regrid_from_file[test_case7] - ValueError: ESMC_MeshCreateFromFile() failed with rc = 67.    Please check ...

With these details:

20250710 162341.479 ERROR            PET0 /Users/sacks/esmf/esmf0/src/Infrastructure/IO/interface/ESMC_IOScrip2ESMF.C:50 handle_error Internal error: Bad condition  - line 572: NetCDF error: NetCDF: HDF error
20250710 162341.479 ERROR            PET0 /Users/sacks/esmf/esmf0/src/Infrastructure/Mesh/src/ESMCI_Mesh_FileIO.C:429 ESMCI_mesh_create_from_ESMFMesh_ The NetCDF Library returned an error  -  Unable to open existing file: .esmf.nc, (PIO/NetCDF error = NetCDF: HDF error)
20250710 162341.479 ERROR            PET0 /Users/sacks/esmf/esmf0/src/Infrastructure/Mesh/src/ESMCI_Mesh_FileIO.C:670 ESMCI_mesh_create_from_ESMFMesh_ The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 /Users/sacks/esmf/esmf0/src/Infrastructure/Mesh/src/ESMCI_Mesh_FileIO.C:1110 ESMCI_mesh_create_from_SCRIP_fil The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 /Users/sacks/esmf/esmf0/src/Infrastructure/Mesh/src/ESMCI_Mesh_FileIO.C:284 ESMCI_mesh_create_from_file() The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 ESMCI_MeshCap.C:2605 MeshCap::meshcreatefromfilenew() The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 ESMF_Mesh.F90:1970 ESMF_MeshCreateFromFile() The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 ESMF_Mesh_C.F90:80 f_esmf_meshcreatefromfile The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 /Users/sacks/esmf/esmf0/src/Infrastructure/Mesh/src/ESMCI_Mesh.C:129 ESMCI::Mesh::createfromfile() The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 ESMCI_MeshCap.C:508 MeshCap::meshcreatefromfile() The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.479 ERROR            PET0 ESMC_Mesh.C:137 ESMC_MeshCreateFromFile() The NetCDF Library returned an error  - Internal subroutine call returned Error
20250710 162341.527 INFO             PET0  Finalizing ESMF

I have a feeling the problem was that we were sometimes using the netcdf
library in the conda environment and sometimes the system-level netcdf.
I don't have time to try to figure this out right now, so for now am
just backing out this inclusion of the netcdf4 library.